package mathexa.com;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.util.Log;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.SeekBar;

import java.util.ArrayList;

public class MainActivity extends AppCompatActivity {

    ListView timesTableListView;


    /*
    we will define a method with an int parameter where
    we'll define how the add automatically a list of numeric values into our ListView object
     */
    public void generateTimesTable(int timesTable) {

        /*
        We will declare an array list variable where we will add our values based on
        for loop statement:
         */
        ArrayList<String> timesTableContent=new ArrayList<String>();
        for(int i=1;i<=10;i++) {
            timesTableContent.add(Integer.toString(i*timesTable));
        }

        /*
        we need also an array adapter used to adapt our array list content to a specific list layout:
         */
        ArrayAdapter<String> arrayAdapter=new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,timesTableContent);
        //we make the link between the content of the array list and the array adaptor:
        timesTableListView.setAdapter(arrayAdapter);
    }



    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        //we want to locate our view objects by their id:
        final SeekBar timesTableSeekBar=(SeekBar) findViewById(R.id.timesTableSeekBar);
        timesTableListView=(ListView) findViewById(R.id.timesTableListView);

        //we will setup the maximum and the progress values of the seek bar:
        timesTableSeekBar.setMax(20);
        timesTableSeekBar.setProgress(10);

        //we are calling the listener to interact with our seek bar:
        timesTableSeekBar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() {
            @Override
            public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {

               /*
               we declared a simple code to get the int values generated by our seek bar listener
                and to pass them to the argument of the method generateTimesTable. In this
                way the Array List is updated with the values provided by the movement of our Seek Bar:
                */
                int min=1;
                int timesTable;
                if(progress<min) {
                    timesTable=min;
                    timesTableSeekBar.setProgress(min);
                }else {
                    timesTable=progress;
                }
                generateTimesTable(timesTable);

                /*
                If we want to check that the seek bar is working we can generate the log information below:
                 */
                Log.i("SeekBar value",Integer.toString(timesTable));
            }

            @Override
            public void onStartTrackingTouch(SeekBar seekBar) {

            }

            @Override
            public void onStopTrackingTouch(SeekBar seekBar) {

            }
        });
/*
we are calling the method to generate automatically the values for our
Array List using the argument 10 as a default value:
 */
generateTimesTable(10);
    }
}